name: Feature request
description: File a feature request.
title: "[request] <title>"
labels: ["featurerequest"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description:
      placeholder:
      value: "Describe your feature request in a few lines"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
